'use client'
import { MOCK_INSIGHTS, MOCK_WEEKLY_DATA } from '@/lib/mock/seed'
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid, Legend } from 'recharts'

export default function SummaryPage() {
  const avg = {
    mental:   Math.round(MOCK_WEEKLY_DATA.reduce((a, d) => a + d.mental,   0) / 7),
    psych:    Math.round(MOCK_WEEKLY_DATA.reduce((a, d) => a + d.psych,    0) / 7),
    physical: Math.round(MOCK_WEEKLY_DATA.reduce((a, d) => a + d.physical, 0) / 7),
  }

  return (
    <div className="animate-in">
      <div className="grid-3" style={{marginBottom:'var(--space-5)'}}>
        {([
          { label:'Avg Mental',   value:avg.mental,   color:'var(--color-mental)',   bg:'var(--color-mental-bg)'   },
          { label:'Avg Psych',    value:avg.psych,    color:'var(--color-psych)',    bg:'var(--color-psych-bg)'    },
          { label:'Avg Physical', value:avg.physical, color:'var(--color-physical)', bg:'var(--color-physical-bg)' },
        ]).map(k => (
          <div key={k.label} className="kpi-card">
            <div className="kpi-icon" style={{background:k.bg}}>
              <div style={{width:10,height:10,borderRadius:'50%',background:k.color}}/>
            </div>
            <div className="kpi-body">
              <div className="kpi-label">{k.label}</div>
              <div className="kpi-value" style={{color:k.color}}>{k.value}<span style={{fontSize:'var(--text-xs)',color:'var(--color-text-muted)',marginLeft:4}}>/100</span></div>
              <div className="kpi-change positive">+5 vs last week</div>
            </div>
          </div>
        ))}
      </div>

      <div className="card" style={{marginBottom:'var(--space-5)'}}>
        <div className="card-header"><div className="card-title">Week 13 — Daily Breakdown</div></div>
        <ResponsiveContainer width="100%" height={200}>
          <BarChart data={MOCK_WEEKLY_DATA} margin={{top:4,right:4,left:-20,bottom:0}}>
            <CartesianGrid strokeDasharray="3 3" stroke="var(--color-divider)" vertical={false}/>
            <XAxis dataKey="day" tick={{fontSize:11,fill:'var(--color-text-muted)'}} axisLine={false} tickLine={false}/>
            <YAxis domain={[0,100]} tick={{fontSize:11,fill:'var(--color-text-muted)'}} axisLine={false} tickLine={false}/>
            <Tooltip contentStyle={{background:'var(--color-surface)',border:'1px solid var(--color-divider)',borderRadius:'var(--radius-lg)',fontSize:12}} labelStyle={{color:'var(--color-text)'}}/>
            <Legend wrapperStyle={{fontSize:12,color:'var(--color-text-muted)'}}/>
            <Bar dataKey="mental"   name="Mental"   fill="#6366f1" radius={[4,4,0,0]}/>
            <Bar dataKey="psych"    name="Psych"    fill="#8b5cf6" radius={[4,4,0,0]}/>
            <Bar dataKey="physical" name="Physical" fill="#10b981" radius={[4,4,0,0]}/>
          </BarChart>
        </ResponsiveContainer>
      </div>

      <div className="card">
        <div className="card-header">
          <div>
            <div className="card-title">AI-Generated Insights</div>
            <div className="card-subtitle">Personalised analysis of your week</div>
          </div>
          <span className="ai-module-badge mock">🤖 Mocked Module</span>
        </div>
        {MOCK_INSIGHTS.map(insight => (
          <div key={insight.ring} className={`highlight-card ${insight.ring}`}>
            <div className="highlight-title">{insight.title}</div>
            <div className="highlight-text">{insight.text}</div>
          </div>
        ))}
        <div style={{marginTop:'var(--space-4)',padding:'var(--space-3)',background:'var(--color-surface-offset)',borderRadius:'var(--radius-lg)',fontSize:'var(--text-xs)',color:'var(--color-text-muted)'}}>
          💡 Insights are currently generated by <code>lib/mock/ai-stubs.ts</code>. Future: connect to the FastAPI cognitive nodes service.
        </div>
      </div>
    </div>
  )
}
